import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Image from 'next/image'
export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Vinits First Blog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <Script src='/sc.js' strategy='lazyOnload'></Script> */}
      <main className={styles.main}>
       
        <div className={styles.imagewrap}>
          {/* <Image className={styles.myImg} src="/homeimg.jpg" width={345.6} height={440.8}></Image> */}
          <Image src="/img.jpg" alt="description of image" className={styles.myImg} width={306} height={204} />
        </div>
        <h2 className={styles.title}>
          First Project with Next.JS
        </h2>



        <div className="blogs">
          <h2 className={styles.h2}>Popular blogs</h2>
          <div className="blogItem">
            <h3>2022 mein JavaScript Kaise sikhe? </h3>
            <p className={styles.p}>JavaScript Language Web app ke logic ke liye use kiya jata hai</p>
            <button className={styles.btn}>Read More</button>
          </div>
          <div className="blogItem">
            <h3>2022 mein JavaScript Kaise sikhe </h3>
            <p className={styles.p}>JavaScript Language Web app ke logic ke liye use kiya jata hai</p>
            <button className={styles.btn}>Read More</button>

          </div>
          <div className="blogItem">
            <h3>2022 mein JavaScript Kaise sikhe </h3>
            <p className={styles.p}>JavaScript Language Web app ke logic ke liye use kiya jata hai</p>
            <button className={styles.btn}>Read More</button>

          </div>
        </div>
      </main>

      <footer className={styles.footer}>

      </footer>
    </div>
  )
}
